### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by pradm007** [data301-2021-summer2/project-group24-project#1]
Hello Group 24, 

My name is Pradeep and I will be giving you some feedback on your project. 

Overall, the project is a fantastic start and there are some suggestions I have that will greatly improve the quality of your project
I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1

- Well Done

## Task 2

- Well Done
- Add few comments briefly describing each step

## Task 3

- Well Done

## Task 4

- Good Work
- Expand on your explanation. Try describing how your findings are addressing the research question. Also, add which plots were primarily responsible in making you reach such a conclusion. 

Overall, well done.

**Comment by feisophie** [comment]
Thank you very much for the feedback, Pradeep.
